name: SBOM Upload

on:
  push:
    branches: [main]

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  #v8.0.0

      - name: Generate SBOM
        run: |
          uv venv
          uv pip install -r requirements.txt
          uvx --from cyclonedx-bom cyclonedx-py environment \
              -o sbom.cdx.json \
              .venv/bin/python

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093  #v3.0.0
        with:
          workload_identity_provider: 'projects/379228030003/locations/global/workloadIdentityPools/github/providers/github-actions'
          service_account: 'dtrack-ci@devops-tools-433123.iam.gserviceaccount.com'
          token_format: 'id_token'
          id_token_audience: '379228030003-nug7attglk5fht4gmp6v8s2b88epnmsq.apps.googleusercontent.com'
          id_token_include_email: true

      - name: Upload SBOM to Dependency-Track
        env:
          TOKEN: ${{ steps.auth.outputs.id_token }}
          PROJECT_NAME: ${{ github.event.repository.name }}
          PROJECT_VERSION: ${{ github.sha }}
        run: |
            curl -sf -X POST "https://dtrack.popgen.rocks/api/v1/bom" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY }}" \
              -F "projectName=$PROJECT_NAME" \
              -F "projectVersion=$PROJECT_VERSION" \
              -F "autoCreate=true" \
              -F "bom=@sbom.cdx.json"
