name: Security Checks

on:
  workflow_dispatch:
  push:

jobs:
  package-scanner:
    runs-on: ubuntu-latest
    name: Python Package Scanner
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          persist-credentials: false

      - uses: populationgenomics/python-package-scanner@7db0863f7646dcd34df1ee5f2911149f67628eb3 # v0
        with:
          mode: pip
          fail-on-vulns: false
          comment-on-pr: true
