name: Security Checks

on:
  workflow_dispatch:
  push:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    name: Pip Audit
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install-all

      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          summary: true
